#!/usr/bin/env bash
# Installs nginx and configures it on a remote server

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx start
