#!/usr/bin/env bash
# installs nginx and configures it on a remote server


apt-get update -y
apt-get install -y nginx

ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html

service nginx status > /dev/null 2>&1 || service nginx start
