#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
apt-get update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
sudo echo 'Hello World!' > /var/www/html/index.html
REDIRECT_CONFIG="location /redirect_me {\\
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\
}"

sudo bash -c "echo -e '$REDIRECT_CONFIG' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
    sudo service nginx start
else
    sudo service nginx restart
fi
