#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt-get update
sudo apt-get install -y nginx 
echo "Hello World!" > index.html
sudo mv index.html /var/www/html


NOT_FOUND_CONFIG="error_page 404 /404.html;\\
location = /404.html {\\
    root /usr/share/nginx/html;\\
    internal;\\
    return 200 'Ceci n\\'est pas une page';\\
}"


sudo sed -i "/error_page 404 \/404.html;/c $NOT_FOUND_CONFIG" /etc/nginx/sites-available/default

sudo service nginx restart
