#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt-get update
sudo apt-get install -y nginx 

# Create a simple index.html for the default page
echo "Hello World!" | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

NOT_FOUND_CONFIG="error_page 404 /404.html;\\
location = /404.html {\\
    root /usr/share/nginx/html;\\
    internal;\\
    return 200 'Ceci n\\'est pas une page';\\
}"

echo -e "$NOT_FOUND_CONFIG" | sudo tee -a /etc/nginx/sites-available/default

sudo service nginx restart
