#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo "ENABLED=1" | tee /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen 430875-lb-01
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 430875-web-01 18.209.224.89:80 check
   server 430875-web-02 	34.227.90.0:80 check
" | tee -a /etc/haproxy/haproxy.cfg

service haproxy start
