#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

counter=1
while [ $counter -le 9 ]
do
    if ((counter == 9))
    then
        echo "Hi"
    fi 
    echo "Best School"
    ((counter++))
done